from .student_form import StudentForm
from .resource_form import ResourceForm
from .staff_form import StaffForm
from .timetable_form import TimetableForm
from .exam_form import ExamForm
from .subject_form import SubjectForm
from .classes_form import ClassesForm
from .calendar_form import CalendarForm
from .results_form import ResultsForm
from .subject_selection_form import SubjectsSelectionForm
from .departments_form import DepartmentForm