from .classesModel import ClassesModel
from .examsModel import ExamsModel
from .groupsModel import GroupsModel
from .newsLetterSubscribers import NewsLetterSubcribersModel
from .permissionsModel import PermissionsModel
from .resourcesModel import ResourcesModel
from .resultsModel import ResultsModel
from .rolesModel import RolesModel
from .schoolCalendarModel import SchoolCalendarModel
from .staffModel import StaffModel
from .studentsModel import StudentsModel
from .subjectsModel import SubjectsModel
from .ticketsModel import TicketsModel
from .timetableModel import TimetableModel
from .visitorsSessionsModel import VistorsSessionModel
from .vistorsModel import VistorsModel